[tasks.fetch-fennel]
run = "bash script/fetch-fennel"

[tasks.render-api-documentation]
run = "script/render-api-documentation"

[tasks.setup-test-deps]
run = "bash ./script/setup-test-deps"

[tasks.test]
depends = ["setup-test-deps"]
run = "bash ./script/test"
