#!/usr/bin/env bash

set -xe

SRC_DIR=${SRC_DIR:-.}
SRC_PREFIX=${SRC_PREFIX:-'nfnl\.'}

DEST_DIR=$1
PROJECT=${PROJECT:-$(basename $DEST_DIR)}
DEST_PREFIX=${DEST_PREFIX:-"$PROJECT.nfnl."}

rm -r "$DEST_DIR/fnl/$PROJECT/nfnl" "$DEST_DIR/lua/$PROJECT/nfnl"
mkdir -p "$DEST_DIR/fnl/$PROJECT/nfnl" "$DEST_DIR/lua/$PROJECT/nfnl"
cp -r "$SRC_DIR/lua/nfnl" "$DEST_DIR/lua/$PROJECT/nfnl"
rsync -R $(rg -l '\[nfnl-macro\]' "$SRC_DIR/fnl/nfnl") "$DEST_DIR/fnl/$PROJECT/nfnl"

fd --no-ignore --extension .fnl . "$DEST_DIR/fnl/$PROJECT/nfnl" --exec sd " :$SRC_PREFIX" " :$DEST_PREFIX"
fd --no-ignore --extension .lua . "$DEST_DIR/lua/$PROJECT/nfnl" --exec sd "\"$SRC_PREFIX" "\"$DEST_PREFIX"
