#!/usr/bin/env bash

FNL_VERSION=1.5.3
FNL_NAME=fennel-$FNL_VERSION

# Executable binary
curl https://fennel-lang.org/downloads/$FNL_NAME >script/fennel.lua
chmod +x script/fennel.lua

# Compiler / library
curl https://fennel-lang.org/downloads/$FNL_NAME.lua >lua/nfnl/fennel.lua
