#!/usr/bin/env bash

FNL_VERSION=1.3.0
FNL_NAME=fennel-$FNL_VERSION

# Executable binary
curl https://fennel-lang.org/downloads/$FNL_NAME >script/fennel.lua
chmod +x script/fennel.lua

# Compiler / library
curl https://fennel-lang.org/downloads/$FNL_NAME.tar.gz | tar -zxv $FNL_NAME/fennel.lua
mv $FNL_NAME/fennel.lua lua/nfnl/fennel.lua
rmdir $FNL_NAME
