#!/usr/bin/env bash

XDG_CONFIG_HOME=$(pwd)/.test-config
export XDG_CONFIG_HOME

XDG_STATE_HOME=$(pwd)/.test-config/state
export XDG_STATE_HOME

nvim --headless .nfnl.fnl -c trust -c qa
nvim --headless -c 'PlenaryBustedDirectory lua/spec'
