#!/usr/bin/env bash

XDG_CONFIG_HOME=$(pwd)/.test-config
export XDG_CONFIG_HOME

XDG_CONFIG_STATE=$(pwd)/.test-config/state
export XDG_CONFIG_STATE

nvim --headless -c 'edit .nfnl.fnl' -c trust -c qa
nvim --headless -c 'PlenaryBustedDirectory lua/spec'
