name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # neovim-version: ["v0.9.5", "v0.10.4", "stable", "nightly"]
        neovim-version: ["v0.9.5", "v0.10.4"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Mise
        uses: jdx/mise-action@v2

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            .test-config/nvim/pack
          key: nfnl-${{ hashFiles('script/setup-test-deps') }}
          restore-keys: nfnl-

      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mise run -t neovim@${{ matrix.neovim-version }} test
