name: Test

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        neovim-version: [ "v0.9.0", "v0.9.1", "stable", "nightly" ]
        os: [ windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - name: Install Neovim plugins
        run: |
          ./script/setup-test-deps
      - name: Test with plenary / busted
        run: |
          ./script/test
