name: Test

on: [ push ]

jobs:
  test:
    runs-on: [windows-latest, ubuntu-latest]
    strategy:
      matrix:
        neovim-version: [ "v0.9.0", "v0.9.1", "stable", "nightly" ]

    steps:
      - uses: actions/checkout@v3
      - uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim-version }}
      - name: Install Neovim plugins
        run: |
          ./script/setup-test-deps
      - name: Test with plenary / busted
        run: |
          ./script/test
