name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        neovim-version: ["v0.9.5", "stable", "nightly"]
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure line endings in git (keep line endings as they're committed)
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}
      - name: Install Neovim plugins
        run: |
          ./script/setup-test-deps
      - name: Test with plenary / busted
        run: |
          ./script/test
